---
name: Build firmwares
on:
  push:
    branches:
    - '2.4'
    - 'main'
    paths-ignore:
    - '**.md'
    - '.github/ISSUE_TEMPLATE/**'
  pull_request:
    branches:
    - '2.4'
    - 'main'
    paths-ignore:
    - '**.md'
    - '.github/ISSUE_TEMPLATE/**'
  create:
    tags:
      - v*

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - NV14
          - T12
          - T16
          - T18
          - T8
          - TLITE
          - TX12
          - TX16S
          - X10
          - X10_ACCESS
          - X12S
          - X7
          - X7_ACCESS
          - X9D
          - X9DP
          - X9DP2019
          - X9LITE
          - X9LITES
          - XLITE
          - XLITES
    container:
      image: ghcr.io/edgetx/edgetx-commit-tests
      volumes:
        - ${{ github.workspace }}:/src
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Build ${{ matrix.target }}
        env:
          FLAVOR: ${{ matrix.target }}
        run: |
          echo "Running firmware build"
          ./tools/build-gh.sh

      - name: Compose release filename
        # https://github.com/actions/checkout/issues/58#issuecomment-614041550
        run: |
          PR_NUMBER=$(echo $GITHUB_REF | awk 'BEGIN { FS = "/" } ; { print $3 }')
          echo "artifact_name=edgetx-firmware-${PR_NUMBER}" >> $GITHUB_ENV

      - name: Package firmware ${{ matrix.target }}
        uses: 'actions/upload-artifact@v2'
        with:
          name: "${{ env.artifact_name }}"
          path: |
            fw.json
            LICENSE
            *.bin
          retention-days: 15
          if-no-files-found: error
